/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int mpc_func_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int mpc_func_casadi_alloc_mem(void);
int mpc_func_casadi_init_mem(int mem);
void mpc_func_casadi_free_mem(int mem);
int mpc_func_casadi_checkout(void);
void mpc_func_casadi_release(int mem);
void mpc_func_casadi_incref(void);
void mpc_func_casadi_decref(void);
casadi_int mpc_func_casadi_n_out(void);
casadi_int mpc_func_casadi_n_in(void);
casadi_real mpc_func_casadi_default_in(casadi_int i);
const char* mpc_func_casadi_name_in(casadi_int i);
const char* mpc_func_casadi_name_out(casadi_int i);
const casadi_int* mpc_func_casadi_sparsity_in(casadi_int i);
const casadi_int* mpc_func_casadi_sparsity_out(casadi_int i);
int mpc_func_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int casadi_dynamics_mpc_dt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int casadi_dynamics_mpc_dt_alloc_mem(void);
int casadi_dynamics_mpc_dt_init_mem(int mem);
void casadi_dynamics_mpc_dt_free_mem(int mem);
int casadi_dynamics_mpc_dt_checkout(void);
void casadi_dynamics_mpc_dt_release(int mem);
void casadi_dynamics_mpc_dt_incref(void);
void casadi_dynamics_mpc_dt_decref(void);
casadi_int casadi_dynamics_mpc_dt_n_out(void);
casadi_int casadi_dynamics_mpc_dt_n_in(void);
casadi_real casadi_dynamics_mpc_dt_default_in(casadi_int i);
const char* casadi_dynamics_mpc_dt_name_in(casadi_int i);
const char* casadi_dynamics_mpc_dt_name_out(casadi_int i);
const casadi_int* casadi_dynamics_mpc_dt_sparsity_in(casadi_int i);
const casadi_int* casadi_dynamics_mpc_dt_sparsity_out(casadi_int i);
int casadi_dynamics_mpc_dt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
