/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int tube_mpc_func_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int tube_mpc_func_casadi_alloc_mem(void);
int tube_mpc_func_casadi_init_mem(int mem);
void tube_mpc_func_casadi_free_mem(int mem);
int tube_mpc_func_casadi_checkout(void);
void tube_mpc_func_casadi_release(int mem);
void tube_mpc_func_casadi_incref(void);
void tube_mpc_func_casadi_decref(void);
casadi_int tube_mpc_func_casadi_n_out(void);
casadi_int tube_mpc_func_casadi_n_in(void);
casadi_real tube_mpc_func_casadi_default_in(casadi_int i);
const char* tube_mpc_func_casadi_name_in(casadi_int i);
const char* tube_mpc_func_casadi_name_out(casadi_int i);
const casadi_int* tube_mpc_func_casadi_sparsity_in(casadi_int i);
const casadi_int* tube_mpc_func_casadi_sparsity_out(casadi_int i);
int tube_mpc_func_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int integrator_func_casadi(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int integrator_func_casadi_alloc_mem(void);
int integrator_func_casadi_init_mem(int mem);
void integrator_func_casadi_free_mem(int mem);
int integrator_func_casadi_checkout(void);
void integrator_func_casadi_release(int mem);
void integrator_func_casadi_incref(void);
void integrator_func_casadi_decref(void);
casadi_int integrator_func_casadi_n_out(void);
casadi_int integrator_func_casadi_n_in(void);
casadi_real integrator_func_casadi_default_in(casadi_int i);
const char* integrator_func_casadi_name_in(casadi_int i);
const char* integrator_func_casadi_name_out(casadi_int i);
const casadi_int* integrator_func_casadi_sparsity_in(casadi_int i);
const casadi_int* integrator_func_casadi_sparsity_out(casadi_int i);
int integrator_func_casadi_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
